In [0]:
import numpy as np
import pandas as pd
import io
#from google.colab import files

In [0]:
#uploaded = files.upload()
df = pd.read_csv(r"C:\Users\nawaz\Downloads\matches.csv")
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [0]:
df.head(3)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN

In [0]:
# Q1. Find the total number of matches played till now in IPL
#since the number of rows is the number of matches played
a=len(df)
print("total number of matches played:",a)

total number of matches played: 636

In [0]:
# Q2. Create a new dataframe from df which will have all the alternate rows and columns from df starting from 0
print(df.shape) #number of rows and coloumns 
df.iloc[1:636:2,1:18:2]

(636, 18)

,season,date,team2,toss_decision,dl_applied,win_by_runs,player_of_match,umpire1,umpire3
1,2017,2017-04-06,Rising Pune Supergiant,field,0,0,SPD Smith,A Nand Kishore,NaN
3,2017,2017-04-08,Kings XI Punjab,field,0,0,GJ Maxwell,AK Chaudhary,NaN
5,2017,2017-04-09,Sunrisers Hyderabad,field,0,0,Rashid Khan,A Deshmukh,NaN
7,2017,2017-04-10,Kings XI Punjab,bat,0,0,AR Patel,AK Chaudhary,NaN
9,2017,2017-04-12,Mumbai Indians,field,0,0,JJ Bumrah,Nitin Menon,NaN
...,...,...,...,...,...,...,...,...,...
627,2016,2016-05-20,Delhi Daredevils,field,0,0,KK Nair,A Nand Kishore,NaN
629,2016,2016-05-21,Gujarat Lions,field,0,0,SK Raina,AK Chaudhary,NaN
631,2016,2016-05-22,Royal Challengers Bangalore,field,0,0,V Kohli,A Nand Kishore,NaN
633,2016,2016-05-25,Kolkata Knight Riders,field,0,22,MC Henriques,M Erasmus,NaN
635,2016,2016-05-29,Royal Challengers Bangalore,bat,0,8,BCJ Cutting,HDPK Dharmasena,NaN

In [0]:
# Q3. Find the number of matches played in Mumbai in the period of 2013 and 2017
mask1=df['city']=='Mumbai' 
mask2= ((df["season"]<=2017)&(df["season"]>=2013))
print("number of matches played in mumbai between 2017 and 2013: ",len(df[mask1 &mask2]))

number of matches played in mumbai between 2017 and 2013:  38

In [0]:
# Q4. Find the number of matches where the margin of victory was greater than 30
x=df[df["win_by_runs"]>30]
print("number of matches where the margin is greater than 30: ",len(x))

number of matches where the margin is greater than 30:  103

In [0]:
# Q5. What percent times KKR decides to bat after winning the toss

In [0]:
m=len(df[(df["toss_winner"]=="Kolkata Knight Riders") & (df["toss_decision"]=="bat")])
n=len(df[df["toss_winner"]=="Kolkata Knight Riders"])
y=m/n*100
print("KKR chose to bat ",y,"% times after winning the toss")

KKR chose to bat  38.46153846153847 % times after winning the toss